language: c
  
branches:
  only:
    - master

matrix:
  allow_failures:
    - os: osx

sudo: required

osx_image: xcode8

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - swig
      - libxml2-dev
      - python-dev
      - python-sphinx
      - doxygen

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libxml2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sphinx  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen ; fi

script:
  rm -fr tmp-build && mkdir -p tmp-build && cd tmp-build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=on -DERROR_HANDLING=on -DWANT_TESTS=on -DWANT_EXAMPLES=on -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH="`pwd`"/install -DCMAKE_C_FLAGS="-Wall -Werror" && make
